### ISSUE TITLE
Help needed to use the code to show all missing buildings

### ISSUE THREAD

**Issue by misibacsi** [hfs/buildings_without_landuse#1]
Hello

I need some help to use this code.

Recently I noticed this project and I became interested to re-create it for Hungary. 
I am a hungarian OSM-editor for years and I am looking for all areas within Hungary where buildings are missing inside settlements.

I am not a programmer, but with try and error I somehow managed to get the codes working with OSM data of Hungary.
I do not intend to use it for Maproulette, I wish to create it for edit the map further.
I successfully received the output .geojson file, and I loaded it into the QGIS software.

The QGIS shows some domains with shaded, colored area, however I noticed that many empty areas are missing and not colored. within settlement boundaries.

I noticed that in "buildings_without_landuse.sql" there are two parameters 
("ST_ClusterDBSCAN(geom, eps := 100, minpoints := 10)") , 
and I tried to change them (200, 400, 750 instead of 100, and 2, 5, 20 instead of 10).

But still not all missing areas are shown. My main purpose would be to see ALL possible areas with missing buildings. 
What direction should I modify the eps and minpoints parameters? Or is it determined by other parameters?

Please give advice how I can go further with this useful code in my little OSM editing project.

**Comment by hfs** [comment]
Hi @misibacsi,

I’m very happy if someone can make use of these projects and I will try to help you.

From your description it sounds like you are looking for residential areas where buildings are missing. It seems that you have mixed up the projects and should take a look at https://github.com/hfs/landuse_without_buildings instead. This project does almost the opposite. It looks at places that already have buildings, but are not surrounded by and landuse polygon.

landuse_without_buildings will probably give you enough results to keep you busy for while. There are a few parameters that control which areas are looked at.

In [landuse_without_buildings.sql, line 117](https://github.com/hfs/landuse_without_buildings/blob/48bfdb51449decbb0caae7b724fbf1bb8acd61f9/landuse_without_buildings.sql#L117) the line `WHERE l.area >= 25000` sets the minimum area in m² of landuse polygons to even look at. At a later step in [export_geojson.sql, lines 14-16](https://github.com/hfs/landuse_without_buildings/blob/48bfdb51449decbb0caae7b724fbf1bb8acd61f9/export_geojson.sql#L14-L16) the condition `WHERE building_fraction <= 0.04 AND area >= 500` controls which result areas to export.

Hope this helps. If you have more questions or problems to run the code, feel free to contact me or open an issue over in the other project.
